//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreetingsBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Greeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Greeting()
        {
            this.GreetingRecipients = new HashSet<GreetingRecipient>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public int Holiday_Id { get; set; }
    
        public virtual Holiday Holiday { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreetingRecipient> GreetingRecipients { get; set; }
    }
}
