//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreetingsBot
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Goodbye> Goodbyes { get; set; }
        public virtual DbSet<Greeting> Greetings { get; set; }
        public virtual DbSet<Hello> Helloes { get; set; }
        public virtual DbSet<GreetingRecipient> GreetingRecipients { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<Recipient> Recipients { get; set; }
        public virtual DbSet<ThanksAnswer> ThanksAnswers { get; set; }
        public virtual DbSet<Howdy> Howdies { get; set; }
    }
}
