//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreetingsBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreetingRecipient
    {
        public int Id { get; set; }
        public int Greeting_Id { get; set; }
        public int Recipient_Id { get; set; }
    
        public virtual Greeting Greeting { get; set; }
        public virtual Recipient Recipient { get; set; }
    }
}
